### PR TITLE
Many options and some bug fixes

### LINKED ISSUE #5: Fingerprint registered, then phone locked doesn't reset glyph
Once a fingerprint is scanned and the animation is complete and on the check mark, if the user has not fully unlocked the phone and locks the phone, once the lock screen is shown again the glyph has is not reset.

### PR DESCRIPTION
**Pull request by AppleBetas**
**Bug fixes:**
- If phone is locked from unlocked lock screen state, fingerprint glyph now resets (Fixes #5)

**New features:**
- Add option to change 'Press home to unlock' label text
- Add option to not hide 'Press home to unlock' label
- Move lock glyph up if label is shown
- Adds option to use old Apple Pay sound (the new sound is now default, the old sound used to be the only option)
- Adds option to use Apple Pay sound instead of current theme's sound
- Adds option to use 'Hold to Reader' animation while idle
- Adds option to use 'Loading' animation while scanning fingerprint

**Other enhancements:**
- New `LockGlyphXPrefsItemsController` class which localizes item `PSLinkListCell` values
- Made LockGlyph default state use defined value, rather than just 0

### CODE REVIEW

**Comment by nullpixel** [comment]
You should probably credit yourself

**Comment by AppleBetas** [comment]
@nullpixel1 I was already credited in the credits menu

**Comment by Sticktron** [comment]
testing it now...

**Comment by nullpixel** [comment]
@AppleBetas dammit, missed that

**Comment by Sticktron** [comment]
Quick question... what does the option "Use loading scan animation" do?

**Comment by AppleBetas** [comment]
While the fingerprint is being scanned, rather than using the fingerprint scanning glyph state, it uses the loading glyph state (a ring with a spinning notch)

**Comment by Sticktron** [comment]
oh ok, I didn't see it because I had "hide ring" turned on

**Comment by Sticktron** [comment]
I'll make that a bit clearer

**Comment by Sticktron** [comment]
Great work. Merging.

**Pull request merged**
