### PR TITLE
Fix up the credits page

### PR DESCRIPTION
**Pull request by nullpixel**
Seems a lot more could be wrong here, but credit URLs now open.

### CODE REVIEW

**Comment by Sticktron** [comment]
oops. fixed.

**Comment by nullpixel** [comment]
So why did you close this?

**Comment by Sticktron** [comment]
I would have had to solve a merge conflict to pull your change so I just moved the twitter functions locally and included it in with AppleBetasDev's commits.

Thanks for fixing that :)

Sent from my iPhone

On Feb 22, 2017, at 2:11 PM, Jamie Bishop <notifications@github.com<mailto:notifications@github.com>> wrote:


So why did you close this?

**Comment by nullpixel** [comment]
I'd have rebased if you asked me, it's literally pressing a button. But whatever

**Pull request closed without merging**
